<?php

$title = 'Add new message:';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('book', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo '*'.$this->formRow($form->get('user_name'));
echo '*'.$this->formRow($form->get('email'));
echo $this->formRow($form->get('home_page'));
echo '*'.$this->formRow($form->get('message'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
echo '* - fields must be required!';