<?php echo 'The site is under development now...' ?>

<h1><?php echo $this->escapeHtml('Guest-Book'); ?></h1>
<!--<p>-->
<!--    <a href="--><?php //echo $this->url('book', array('action'=>'add'));?><!--">Add new message</a>-->
<!--</p>-->

<table class="table">
    <tr>
        <th>User name</th>
        <th>E-mail</th>
        <th>Home page</th>
        <th>Message</th>
        <th>Date of the publication</th>
        <th>&nbsp;</th>
    </tr>

    <?php foreach ($books as $book) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($book->user_name);?></td>
            <td><?php echo $this->escapeHtml($book->email);?></td>
            <td><?php echo $this->escapeHtml($book->home_page);?></td>
            <td><?php echo $this->escapeHtml($book->message);?></td>
            <td><?php echo date('d F Y H:i:s', $this->escapeHtml($book->message_date));?></td>
            <td>
<!--               <a href="--><?php //echo $this->url('book',
//                    array('action'=>'edit', 'id' => $book->id));?><!--">Edit</a>-->
                <a href="<?php echo $this->url('book',
                    array('action'=>'delete', 'id' => $book->id));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>

</table>


    <h3><?php echo $this->escapeHtml('Add new message:'); ?></h3>
<?php
//$form->setAttribute('action', $this->url('book', array('action' => 'add')));
$form=(object)$form;
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo '*'.$this->formRow($form->get('user_name')).'<br/>';
echo '*'.$this->formRow ($form->get('email')).'<br/>';
echo $this->formRow($form->get('home_page')).'<br/>';
echo '*'.$this->formRow($form->get('message')).'<br/>';
echo $this->formReset($form->get('button'));
echo $this->formHidden($form->get('user_ip'));
echo $this->form()->closeTag();
echo '* - fields must be required!';
?>


